set(CMAKE_SYSTEM_NAME "ESP8266")
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_CROSSCOMPILING TRUE)

set(UNIX 1)
set(WIN32)
set(APPLE)

if (NOT "${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
endif ()

set(CMAKE_C_OUTPUT_EXTENSION .o)
set(CMAKE_CXX_OUTPUT_EXTENSION .o)
set(CMAKE_ASM_OUTPUT_EXTENSION .o)
set(CMAKE_STATIC_LIBRARY_PREFIX lib)
set(CMAKE_STATIC_LIBRARY_SUFFIX .a)
set(CMAKE_SHARED_LIBRARY_PREFIX lib)
set(CMAKE_SHARED_LIBRARY_SUFFIX .a)
set(CMAKE_EXECUTABLE_SUFFIX .elf)
