message("****** TOOLS")
message("Hier ARDUINO_ESP8266_TOOLS: ${ARDUINO_ESP8266_TOOLS}")
message("Hier ARDUINO_ESP8266_DIR: ${ARDUINO_ESP8266_DIR}")
message("Hier ARDUINO_USER: ${ARDUINO_USER}")
if("${ARDUINO_ESP8266_TOOLS}" STREQUAL "")
    message("check ${ARDUINO_ESP8266_DIR}/tools/xtensa-lx106-elf")
    if(EXISTS "${ARDUINO_ESP8266_DIR}/tools/xtensa-lx106-elf")
    message("found ${ARDUINO_ESP8266_DIR}/tools/xtensa-lx106-elf")
        set(ARDUINO_ESP8266_TOOLS "${ARDUINO_ESP8266_DIR}/tools" CACHE PATH "Path to the directory containing ESP8266 tools")
    endif()
endif()
if("${ARDUINO_ESP8266_TOOLS}" STREQUAL "" AND NOT "${ARDUINO_USER}" STREQUAL "")
    if(EXISTS "${ARDUINO_USER}/packages/esp8266/tools/xtensa-lx106-elf")
        set(ARDUINO_ESP8266_TOOLS "${ARDUINO_USER}/packages/esp8266/tools" CACHE PATH "Path to the directory containing ESP8266 tools")
    endif()
endif()
if(NOT "${ARDUINO_ESP8266_TOOLS}" STREQUAL "")
    message(STATUS "Using ARDUINO_ESP8266_TOOLS ${ARDUINO_ESP8266_TOOLS}")
else()
    message(FATAL_ERROR "ARDUINO_ESP8266_TOOLS is not set and ESP8266 tools could not be found")
endif()
