if (CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
    set(ESP8266_DEFAULT_ARDUINO_USER "$ENV{HOME}/.arduino15")
    set(ESP8266_EXEC_SUFFIX "")
elseif (CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
    if (IS_DIRECTORY "$ENV{ProgramFiles\(x86\)}/Arduino")
        set(ESP8266_DEFAULT_ARDUINO_HOME "$ENV{ProgramFiles\(x86\)}/Arduino")
    elseif (IS_DIRECTORY "$ENV{ProgramFiles}/Arduino")
        set(ESP8266_DEFAULT_ARDUINO_HOME "$ENV{ProgramFiles}/Arduino")
    endif ()
    set(ESP8266_DEFAULT_ARDUINO_USER "$ENV{LOCALAPPDATA}/Arduino15")
    set(ESP8266_EXEC_SUFFIX ".exe")
else ()
    message(FATAL_ERROR "Unsupported build platform ${CMAKE_HOST_SYSTEM_NAME}")
endif ()

if("${ARDUINO_HOME}" STREQUAL "")
    set(ARDUINO_HOME "${ESP8266_DEFAULT_ARDUINO_HOME}")
    message(STATUS "Using ARDUINO_HOME ${ARDUINO_HOME}")
endif()
if("${ARDUINO_USER}" STREQUAL "")
    set(ARDUINO_USER "${ESP8266_DEFAULT_ARDUINO_USER}")
    message(STATUS "Using ARDUINO_USER ${ARDUINO_USER}")
endif()
